### ISSUE TITLE
Error when installing using go get ....

### ISSUE THREAD

**Issue by dtickell** [nonoo/kappanhang#10]
Hi

Attempting to install this on raspbarian with recently installed golang package I get this error
# go.uber.org/multierr
go/src/go.uber.org/multierr/error.go:197:6: undefined: errors.As
go/src/go.uber.org/multierr/error.go:210:6: undefined: errors.Is

I am able to install other packages, and have tried this on two raspberry PI 4's 

Any suggestions welcome.

Daniel

**Comment by nonoo** [comment]
Make sure you use the latest version of the OS with an up-to-date golang package. The multierr package should have version v1.6.0, you can check it's version with `ls $GOPATH/pkg/mod/go.uber.org/`
