### ISSUE TITLE
ALSA support - and GPS via virtual Serial

### ISSUE THREAD

**Issue by zompiexx** [nonoo/kappanhang#11]
First of all, thanks for writing such a great bit of code.

Is there a way to enable ALSA support for the audio? A number of software modems that I use, such as Direwolf and Ardop, only have support for ALSA and not pulseaudio.

Unfortunately, this means that I have to plug a USB cable in just to use the software modems.

Also, is there a way to present the GPS feed from the radio as a second virtual serial device?

Thanks in advance,

Andy, UK

**Comment by nonoo** [comment]
Make sure you have the dmix ALSA plugin installed and then I think you'll be able to use Pulseaudio with legacy software. I don't plan to add native ALSA support.

The transceiver does not provide GPS data over IP.

**Comment by zompiexx** [comment]
Hi Norbert:

Thanks for the quick reply, I’ll give that a try.

Best regards,

Andy

**Comment by Gymnae** [comment]
A note regarding GPS via IP: While GPS data is not transmitted, firmware v24 now has the ic-705 act as an NTP server when operating in hotspot mode. This might not help APRS, but it does digimodes.

**Comment by giordyb** [comment]
> A note regarding GPS via IP: While GPS data is not transmitted, firmware v24 now has the ic-705 act as an NTP server when operating in hotspot mode. This might not help APRS, but it does digimodes.

@Gymnae do you mind sharing where did you found out about this? I couldn't find any mentions of this feature in the manuals and port 123 (NTP) is not open on the 705 when in hotspot mode.

**Comment by gymnae** [comment]
@giordyb coming back to this old question I have to say I wonder myself now where I got this from and how I arrived at that conclusion. Out in the field I witnessed time drift, so I don't think my comment hold water. But I will try to recall how I arrived at that conclusion
