### ISSUE TITLE
Internal rigctld does not support extended commands

### ISSUE THREAD

**Issue by georges** [nonoo/kappanhang#15]
I'm new to this so I could be missing something basic. However it seems that the internal rigctld process does not support the extended version of the commands. The pat winlink client seems to be issuing those commands when using hamlib as rig control.

STR:
1. Run kappanhang
2. Configure pat to use hamlib https://github.com/la5nta/pat/wiki/Rig-control
3. Run pat interactive
4. Enter command: freq

Notice in the kappanhang console the following line:

error rigctld@409: got unknown cmd \get_freq

Alternatively if I telnet to rigctld directly and try get_freq or other variation I get an error. If I type f I get the proper response.

**Comment by nonoo** [comment]
Yes, only the short commands are supported.
