### ISSUE TITLE
kappanhang as a RS-BA1 server?

### ISSUE THREAD

**Issue by TheSkorm** [nonoo/kappanhang#17]
Hey this is a really cool project. Do you think it's possible to implement the inverse and have kappanhang act as a RS-BA1 server.
<img width="276" alt="03-3" src="https://user-images.githubusercontent.com/234867/130386024-e89ba8b7-5adc-44ee-8cba-41299e7cc7fb.png">

The use case would be connecting to an IC-7100 using a raspberrypi as a gateway instead of a Windows machine.

**Comment by nonoo** [comment]
Yes, it would be possible to add server functionality.
