### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by sm0tsc** [nonoo/kappanhang#2]
Trying to install on a Raspberry PI

I encounter

root@raspberrypi:~# go get https://github.com/nonoo/kappanhang
package https:/github.com/nonoo/kappanhang: https:/github.com/nonoo/kappanhang: invalid import path: malformed import path "https:/github.com/nonoo/kappanhang": invalid char ':'
root@raspberrypi:~#

Please advise

//SM0TSC - Johan

**Comment by nonoo** [comment]
What is the exact command you enter?

**Comment by sm0tsc** [comment]
go get https://github.com/nonoo/kappanhang


//Johan

Den lör 5 dec. 2020 kl 22:16 skrev Norbert Varga <notifications@github.com>:

**Comment by nonoo** [comment]
Try entering github.com/nonoo/kappanhang (no https://)

**Comment by sm0tsc** [comment]
> Try entering github.com/nonoo/kappanhang (no https://)

That worked, but your readme.md says with https:// :-)

Tnx for hint

//Johan - SM0TSC
