### ISSUE TITLE
Errors on Install

### ISSUE THREAD

**Issue by thetacojoe** [nonoo/kappanhang#25]
I attempted to install kappanhang on my Raspberry Pi 3B+ running 32-bit bullseye and got the following messages:

go get github.com/nonoo/kappanhang
go install github.com/nonoo/kappanhang
found packages unix (affinity_linux.go) and main (mkasm.go) in /home/pi/go/src/golang.org/x/sys/unix
go/src/github.com/mattn/go-isatty/isatty_tcgets.go:8:8: found packages unix (affinity_linux.go) and main (mkasm.go) in /home/pi/go/src/golang.org/x/sys/unix

This is on a fresh install of Raspberry Pi OS and I have had it work before on other installations a very long time ago.

**Comment by nonoo** [comment]
Builds and compiles fine with go 1.21.5 on x64. I don't know what's causing your Raspberry Pi issue. Try upgrading go.

**Comment by thetacojoe** [comment]
Thank you for responding, upgrading go ultimately worked. The version in the repository for Raspberry Pi OS 32-bit Bullseye was an older version. Using the latest version downloaded directly from the go website was required.

It also required the following command after installing go as I was getting a "go.mod file not found" error message:
go env -w GO111MODULE=off

It all works now.
