### ISSUE TITLE
Cannot install Kappanhang

### ISSUE THREAD

**Issue by luarvique** [nonoo/kappanhang#27]
Instructions given on GitHub do not install Kappanhang into ${HOME}/go/bin as advertised. Using Debian Bullseye on Raspberry Pi CM4.  Entered the following:
```
sudo apt install golang libpulse-dev
go get github.com/nonoo/kappanhang
go install github.com/nonoo/kappanhang
```
Go responded to each invocation with this message:
`go/src/github.com/mattn/go-isatty/isatty_tcgets.go:8:8: found packages unix (affinity_linux.go) and main (mkasm.go) in /home/fms/go/src/golang.org/x/sys/unix
`
Afterwards, there is no ${HOME}/go/bin folder:
```
$ ls ${HOME}/go
src
```

**Comment by nonoo** [comment]
You are using an old version of go. Update it.
